runtime: python39

entrypoint: gunicorn -b :$PORT app:app

instance_class: F1

env_variables:
  SECRET_KEY: 'secret-key'
  SQLALCHEMY_DATABASE_URI: 'sqlite:///finance_tracker.db'

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
