version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.9

jobs:
  build_and_test:
    executor: python-executor
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y python3-venv
      - run: python3 -m venv venv
      - run: . venv/bin/activate
      - run: pip install -r requirements.txt
      - run: pytest

  deploy:
    executor: python-executor
    steps:
      - checkout
      - run: echo $GOOGLE_SERVICE_ACCOUNT_KEY > service_account_key.json
      - run: sudo apt-get update
      - run: sudo apt-get install -y google-cloud-sdk
      - run: gcloud auth activate-service-account --key-file service_account_key.json
      - run: gcloud config set project <YOUR_REPO_NAME>
      - run: |
          gcloud compute ssh <YOUR_GCE_INSTANCE> --command "git pull" --zone=<YOUR_INSTANCE_ZONE>
          gcloud compute ssh <YOUR_GCE_INSTANCE> --command "sudo pkill -f app.py" --zone=<YOUR_INSTANCE_ZONE>
          gcloud compute ssh <YOUR_GCE_INSTANCE> --command ". venv/bin/activate && nohup python app.py > app.log 2>&1 &" --zone=<YOUR_INSTANCE_ZONE>

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: main
