version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.9

jobs:
  build_and_test:
    executor: python-executor
    steps:
      - checkout
      - run: sudo pip install virtualenv
      - run: virtualenv --clear -p python3 venv
      - run: . venv/bin/activate
      - run: pip install -r requirements.txt

  deploy:
    executor: python-executor
    steps:
      - checkout
      - run: echo $GOOGLE_SERVICE_ACCOUNT_KEY > service_account_key.json
      - run: sudo apt-get update
      - run: echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
      - run: curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
      - run: sudo apt-get update
      - run: sudo apt-get install -y google-cloud-sdk
      - run: gcloud auth activate-service-account --key-file service_account_key.json
      - run: gcloud config set project finance-tracker-383004
      - run: |
          gcloud compute ssh finance --command "git pull" --zone=us-central1-a
          gcloud compute ssh finance --command "sudo pkill -f app.py" --zone=us-central1-a
          gcloud compute ssh finance --command ". venv/bin/activate && nohup python app.py > app.log 2>&1 &" --zone=us-central1-a


workflows:
  version: 2
  build-deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: dev1
