version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.9

jobs:
  build:
    executor: python-executor
    steps:
      - checkout
      - run: pip install -r requirements.txt
      
  deploy:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Setup Google Cloud SDK
          command: |
            echo 'export PATH=$PATH:/home/circleci/google-cloud-sdk/bin' >> $BASH_ENV
            source $BASH_ENV
            sudo apt-get install -y google-cloud-sdk
      - run:
          name: Deploy to Google App Engine
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud config set project $GCLOUD_PROJECT
            gcloud -q app deploy app.yaml

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main  
